export const POST_REGISTER_REQUEST = 'Register/POST_REGISTER_REQUEST';
export const POST_REGISTER_SUCCESS = 'Register/POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILED = 'Register/POST_REGISTER_FAILED';
