// GET Bookmark
export const GET_BOOKMARK_REQUEST = 'Bookmark/GET_BOOKMARK_REQUEST';
export const GET_BOOKMARK_SUCCESS = 'Bookmark/GET_BOOKMARK_SUCCESS';
export const GET_BOOKMARK_FAILED = 'Bookmark/GET_BOOKMARK_FAILED';

// Create Bookmark
export const CREATE_BOOKMARK_REQUEST = 'Bookmark/CREATE_BOOKMARK_REQUEST';
export const CREATE_BOOKMARK_SUCCESS = 'Bookmark/CREATE_BOOKMARK_SUCCESS';
export const CREATE_BOOKMARK_FAILED = 'Bookmark/CREATE_BOOKMARK_FAILED';
