export const GET_BOOKMARK_REQUEST = 'Bookmark/GET_BOOKMARK_REQUEST';
export const GET_BOOKMARK_SUCCESS = 'Bookmark/GET_BOOKMARK_SUCCESS';
export const GET_BOOKMARK_FAILED = 'Bookmark/GET_BOOKMARK_FAILED';
