export const GET_PROFILE_REQUEST = 'Profile/GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'Profile/GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'Profile/GET_PROFILE_FAILED';

export const GET_MY_POST_REQUEST = 'Profile/GET_MY_POST_REQUEST';
export const GET_MY_POST_SUCCESS = 'Profile/GET_MY_POST_SUCCESS';
export const GET_MY_POST_FAILED = 'Profile/GET_MY_POST_FAILED';
